<<<<<<< HEAD
# config/routes.yaml

# Routes pour le Patient
patient_login:
    path: /login-patient
    controller: App\Controller\PatientController::loginPatient

liste_medecins:
    path: /medecins
    controller: App\Controller\PatientController::listeMedecins

prendre_rendez_vous:
    path: /prendre-rendez-vous/{id}
    controller: App\Controller\PatientController::prendreRendezVous

# Routes pour le Médecin
medecin_login:
    path: /login-medecin
    controller: App\Controller\MedecinController::loginMedecin

medecin_liste_rdv:
    path: /medecin/rdv
    controller: App\Controller\MedecinController::listeRendezVous

medecin_rendez_vous_demandes:
    path: /medecin/rdv/demandes
    controller: App\Controller\MedecinController::rendezVousDemandes

medecin_modifier_etat_rdv:
    path: /medecin/rdv/modifier-etat/{id}
    controller: App\Controller\MedecinController::modifierEtatRendezVous

medecin_preferences:
    path: /medecin/preferences
    controller: App\Controller\MedecinController::preferences

# Routes de test (simulation de session)
test_session_patient:
    path: /test/session/patient
    controller: App\Controller\TestController::simulatePatientSession

test_session_medecin:
    path: /test/session/medecin
    controller: App\Controller\TestController::simulateMedecinSession

# config/routes.yaml

accepter_rendez_vous:
    path: /medecin/rendez-vous/{id}/accepter
    controller: App\Controller\MedecinController::accepterRendezVous
    methods: POST

refuser_rendez_vous:
    path: /medecin/rendez-vous/{id}/refuser
    controller: App\Controller\MedecinController::refuserRendezVous
    methods: POST

# config/routes.yaml

modifier_date_rendez_vous:
    path: /medecin/rendez-vous/{id}/modifier-date
    controller: App\Controller\MedecinController::modifierDateRendezVous
    methods: [GET, POST]

annuler_rendez_vous:
    path: /medecin/rendez-vous/{id}/annuler
    controller: App\Controller\MedecinController::annulerRendezVous
    methods: POST
    
modifier_types_rendez_vous:
    path: /medecin/modifier-types-rendez-vous
    controller: App\Controller\MedecinController::modifierTypesRendezVous
    methods: [GET, POST]            
mes_consultations:
    path: /mes-consultations
    controller: App\Controller\PatientController::mesConsultations
    methods: GET    
=======
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
>>>>>>> Front_Back_Office
