parameters:
    photo_dir: "%kernel.project_dir%/public/upload/images"
    app.email_sender: '%env(APP_EMAIL_SENDER)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # config/services.yaml
    App\Service\EmailService:
        arguments:
            $smtpUsername: '%env(SMTP_USERNAME)%'

    App\Service\:
        resource: '../src/Service/'
        autowire: true
        autoconfigure: true
